#### Introduction
NumPy is a Python package. It stands for 'Numerical Python'. It is a library consisting of multidimensional array objects and a collection of routines for processing of array.

Numeric, the ancestor of NumPy, was developed by Jim Hugunin. Another package Numarray was also developed, having some additional functionalities. In 2005, Travis Oliphant created NumPy package by incorporating the features of Numarray into Numeric package. There are many contributors to this open source project.

Operations using NumPy
#### Using NumPy, a developer can perform the following operations −

Mathematical and logical operations on arrays.

Fourier transforms and routines for shape manipulation.

Operations related to linear algebra. NumPy has in-built functions for linear algebra and random number generation.

#### Data type
NumPy supports a much greater variety of numerical types than Python does. The following table shows different scalar data types defined in NumPy.

#### 1	
bool_

Boolean (True or False) stored as a byte

#### 2	
int_

Default integer type (same as C long; normally either int64 or int32)

#### 3	
intc

Identical to C int (normally int32 or int64)

#### 4	
intp

Integer used for indexing (same as C ssize_t; normally either int32 or int64)

#### 5	
int8

Byte (-128 to 127)

#### 6	
int16

Integer (-32768 to 32767)

#### 7	
int32

Integer (-2147483648 to 2147483647)

#### 8	
int64

Integer (-9223372036854775808 to 9223372036854775807)

#### 9	
uint8

Unsigned integer (0 to 255)

#### 10	
uint16

Unsigned integer (0 to 65535)

#### 11	
uint32

Unsigned integer (0 to 4294967295)

#### 12	
uint64

Unsigned integer (0 to 18446744073709551615)

#### 13	
float_

Shorthand for float64

#### 14	
float16

Half precision float: sign bit, 5 bits exponent, 10 bits mantissa

#### 15	
float32

Single precision float: sign bit, 8 bits exponent, 23 bits mantissa

#### 16	
float64

Double precision float: sign bit, 11 bits exponent, 52 bits mantissa

### Example

In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [6]:
# using array-scalar type 
import numpy as np 
dt = np.dtype(np.int32) 
print(dt)

int32


## NumPy - Array Attributes

### ndarray.shape
This array attribute returns a tuple consisting of array dimensions. It can also be used to resize the array.

#### Example 1

In [7]:
import numpy as np 
a = np.array([[1,2,3],[4,5,6]]) 
print (a.shape)

(2, 3)


In [ ]:
# this resizes the ndarray 
import numpy as np 

a = np.array([[1,2,3],[4,5,6]]) 

a.shape = (3,2) 
print(a)

[[1 2]
 [3 4]
 [5 6]]


### ndarray.ndim
This array attribute returns the number of array dimensions.

In [10]:
# an array of evenly spaced numbers 
import numpy as np 
a = np.arange(24) 
print (a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


### numpy.itemsize
This array attribute returns the length of each element of array in bytes

In [12]:
# dtype of array is int8 (1 byte) 
import numpy as np 
x = np.array([1,2,3,4,5], dtype = np.int8) 
print (x.itemsize)

1


## NumPy - Array Creation 
A new ndarray object can be constructed by any of the following array creation routines or using a low-level ndarray constructor.

### numpy.empty
It creates an uninitialized array of specified shape and dtype. It uses the following constructor −

numpy.empty(shape, dtype = float, order = 'C')

In [14]:
import numpy as np 
x = np.empty([3,2], dtype = int) 
print(x)

[[1 2]
 [3 4]
 [5 6]]


### numpy.zeros
Returns a new array of specified size, filled with zeros.

numpy.zeros(shape, dtype = float, order = 'C')

In [15]:
# array of five zeros. Default dtype is float 
import numpy as np 
x = np.zeros(5) 
print(x)

[0. 0. 0. 0. 0.]


## NumPy - Indexing & Slicing

 items in ndarray object follows zero-based index. Three types of indexing methods are available − field access, basic slicing and advanced indexing.

Basic slicing is an extension of Python's basic concept of slicing to n dimensions. A Python slice object is constructed by giving start, stop, and step parameters to the built-in slice function. This slice object is passed to the array to extract a part of array.

In [16]:
import numpy as np 
a = np.arange(10) 
s = slice(2,7,2) 
print(a[s])

[2 4 6]


In [19]:

# 2 se 7 ke bich ka number 2 ke diffrence pe print karega
import numpy as np 
a = np.arange(10) 
b = a[2:7:2] 
print(b)

[2 4 6]


In [22]:
import numpy as np 
a = np.arange(20)

#  5 se laekae 20 tak value print karega
print (a[5:])

#  2 se laekae 20 tak value print karega 3 ke diffrence ke sath
print (a[2: :3])


[ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 2  5  8 11 14 17]


## NumPy - Broadcasting

The term broadcasting refers to the ability of NumPy to treat arrays of different shapes during arithmetic operations. Arithmetic operations on arrays are usually done on corresponding elements. If two arrays are of exactly the same shape, then these operations are smoothly performed.



In [24]:
import numpy as np 

a = np.array([1,2,3,4]) 
b = np.array([10,20,30,40]) 
c = a * b 
print(c)

[ 10  40  90 160]


In [26]:
import numpy as np 
a = np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]]) 
b = np.array([1.0,2.0,3.0])  
   
print( 'First array:') 
print (a) 
   
print ('Second array:' )
print(b) 
   
print ('First Array + Second Array' )
print (a + b)

First array:
[[ 0.  0.  0.]
 [10. 10. 10.]
 [20. 20. 20.]
 [30. 30. 30.]]
Second array:
[1. 2. 3.]
First Array + Second Array
[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]


## NumPy - Iterating Over Array
NumPy package contains an iterator object numpy.nditer. It is an efficient multidimensional iterator object using which it is possible to iterate over an array. Each element of an array is visited using Python’s standard Iterator interface.

Let us create a 3X4 array using arange() function and iterate over it using nditer

In [27]:
import numpy as np
a = np.arange(0,60,5)
a = a.reshape(3,4)

print ('Original array is:')
print (a)
print ('\n')

print ('Modified array is:')
for x in np.nditer(a):
   print (x)

Original array is:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


Modified array is:
0
5
10
15
20
25
30
35
40
45
50
55


### Iteration Order
If the same elements are stored using F-style order, the iterator chooses the more efficient way of iterating over an array.

Example 1

In [28]:
import numpy as np
a = np.arange(0,60,5)
a = a.reshape(3,4)
print ('Original array is:')
print (a)
print ('\n')

print ('Transpose of the original array is:')
b = a.T
print (b)
print ('\n')

print ('Sorted in C-style order:')
c = b.copy(order = 'C')
print (c)
for x in np.nditer(c):
   print (x)

print ('\n')

print ('Sorted in F-style order:')
c = b.copy(order = 'F')
print (c)
for x in np.nditer(c):
   print (x)

Original array is:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


Transpose of the original array is:
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]


Sorted in C-style order:
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]
0
20
40
5
25
45
10
30
50
15
35
55


Sorted in F-style order:
[[ 0 20 40]
 [ 5 25 45]
 [10 30 50]
 [15 35 55]]
0
5
10
15
20
25
30
35
40
45
50
55


Modifying Array Values
The nditer object has another optional parameter called op_flags. Its default value is read-only, but can be set to read-write or write-only mode. This will enable modifying array elements using this iterator.

In [29]:
import numpy as np
a = np.arange(0,60,5)
a = a.reshape(3,4)
print ('Original array is:')
print (a)
print ('\n')

for x in np.nditer(a, op_flags = ['readwrite']):
   x[...] = 2*x
print ('Modified array is:')
print (a)

Original array is:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


Modified array is:
[[  0  10  20  30]
 [ 40  50  60  70]
 [ 80  90 100 110]]


### Broadcasting Iteration
If two arrays are broadcastable, a combined nditer object is able to iterate upon them concurrently. Assuming that an array a has dimension 3X4, and there is another array b of dimension 1X4, the iterator of following type is used (array b is broadcast to size of a).

In [30]:
import numpy as np 
a = np.arange(0,60,5) 
a = a.reshape(3,4) 

print ('First array is:') 
print (a) 
print ('\n')  

print ('Second array is:') 
b = np.array([1, 2, 3, 4], dtype = int) 
print (b)  
print ('\n') 

print ('Modified array is:') 
for x,y in np.nditer([a,b]): 
   print ("%d:%d" % (x,y))

First array is:
[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


Second array is:
[1 2 3 4]


Modified array is:
0:1
5:2
10:3
15:4
20:1
25:2
30:3
35:4
40:1
45:2
50:3
55:4


## NumPy - Array Manipulation


###  Operations on Numpy Arrays

NumPy is a Python package which means ‘Numerical Python’. It is the library for logical computing, which contains a powerful n-dimensional array object, gives tools to integrate C, C++ and so on. It is likewise helpful in linear based math, arbitrary number capacity and so on. NumPy exhibits can likewise be utilized as an effective multi-dimensional compartment for generic data. NumPy Array: Numpy array is a powerful N-dimensional array object which is in the form of rows and columns. We can initialize NumPy arrays from nested Python lists and access it elements. A Numpy array on a structural level is made up of a combination of:

The Data pointer indicates the memory address of the first byte in the array.
The Data type or dtype pointer describes the kind of elements that are contained within the array.
The shape indicates the shape of the array.
The strides are the number of bytes that should be skipped in memory to go to the next element.
Operations on Numpy Array


### Arithmetic Operations: 

In [32]:
# Python code to perform arithmetic
# operations on NumPy array


import numpy as np


# Initializing the array
arr1 = np.arange(4, dtype = np.float_).reshape(2, 2)

print('First array:')
print(arr1)

print('\nSecond array:')
arr2 = np.array([12, 12])
print(arr2)

print('\nAdding the two arrays:')
print(np.add(arr1, arr2))

print('\nSubtracting the two arrays:')
print(np.subtract(arr1, arr2))

print('\nMultiplying the two arrays:')
print(np.multiply(arr1, arr2))

print('\nDividing the two arrays:')
print(np.divide(arr1, arr2))


First array:
[[0. 1.]
 [2. 3.]]

Second array:
[12 12]

Adding the two arrays:
[[12. 13.]
 [14. 15.]]

Subtracting the two arrays:
[[-12. -11.]
 [-10.  -9.]]

Multiplying the two arrays:
[[ 0. 12.]
 [24. 36.]]

Dividing the two arrays:
[[0.         0.08333333]
 [0.16666667 0.25      ]]


### numpy.reciprocal()
This function returns the reciprocal of argument, element-wise. For elements with absolute values larger than 1, the result is always 0 and for integer 0, overflow warning is issued. Example: 

In [33]:
# Python code to perform reciprocal operation
# on NumPy array
import numpy as np
arr = np.array([25, 1.33, 1, 1, 100])

print('Our array is:')
print(arr)

print('\nAfter applying reciprocal function:')
print(np.reciprocal(arr))

arr2 = np.array([25], dtype = int)
print('\nThe second array is:')
print(arr2)

print('\nAfter applying reciprocal function:')
print(np.reciprocal(arr2))


Our array is:
[ 25.     1.33   1.     1.   100.  ]

After applying reciprocal function:
[0.04      0.7518797 1.        1.        0.01     ]

The second array is:
[25]

After applying reciprocal function:
[0]


### numpy.power() 
This function treats elements in the first input array as the base and returns it raised to the power of the corresponding element in the second input array. 

In [34]:
# Python code to perform power operation
# on NumPy array


import numpy as np


arr = np.array([5, 10, 15])

print('First array is:')
print(arr)

print('\nApplying power function:')
print(np.power(arr, 2))

print('\nSecond array is:')
arr1 = np.array([1, 2, 3])
print(arr1)

print('\nApplying power function again:')
print(np.power(arr, arr1))


First array is:
[ 5 10 15]

Applying power function:
[ 25 100 225]

Second array is:
[1 2 3]

Applying power function again:
[   5  100 3375]


### numpy.mod()
This function returns the remainder of division of the corresponding elements in the input array. The function numpy.remainder() also produces the same result. 



In [35]:
# Python code to perform mod function
# on NumPy array


import numpy as np


arr = np.array([5, 15, 20])
arr1 = np.array([2, 5, 9])

print('First array:')
print(arr)

print('\nSecond array:')
print(arr1)

print('\nApplying mod() function:')
print(np.mod(arr, arr1))

print('\nApplying remainder() function:')
print(np.remainder(arr, arr1))


First array:
[ 5 15 20]

Second array:
[2 5 9]

Applying mod() function:
[1 0 2]

Applying remainder() function:
[1 0 2]
